### PR TITLE
Added a mod description and added Asyncronous to the author list in mcmod.info.

### PR DESCRIPTION
**Pull request by evieluvsrainbows**
Title says it all. :smiley:

### CODE REVIEW

**Comment by s0cks** [comment]
Actually my MCF name is Asyncronous, so please change it to that before I merge it :)

**Comment by evieluvsrainbows** [comment]
@s0cks Alright, updated & commited. :)

**Comment by dmillerw** [comment]
'tis _lets_ in this case, not _let's_, no?

**Comment by evieluvsrainbows** [comment]
@dmillerw Um, I fetched the description from the Remote IO Curse page: http://minecraft.curseforge.com/mc-mods/67593-remote-io :smiley: 

But I'll fix it anyway. :smile:

**Pull request merged**
